### ISSUE TITLE
请问您配置的环境的版本

### ISSUE THREAD

**Issue by shanxiongfei** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#40]
您好，感谢您的分享。我想询问一下你的环境配置的各个版本。我使用的是tensorflow1.11，CUDA9.0，cudnn7.2.1，python2.7.12，但是我在inference.py时，出现下述问题：Traceback (most recent call last):
  File "inference.py", line 127, in <module>
    inference(det_net, data_dir=args.data_dir)
  File "inference.py", line 36, in inference
    gtboxes_r_batch=None)
  File "../libs/networks/build_whole_network.py", line 538, in build_whole_detection_network
    img_shape=img_shape)
  File "../libs/networks/build_whole_network.py", line 154, in postprocess_fastrcnn_r
    use_gpu=cfgs.ROTATE_NMS_USE_GPU)
  File "../libs/box_utils/nms_rotate.py", line 31, in nms_rotate
    device_id=gpu_id)
  File "../libs/box_utils/nms_rotate.py", line 101, in nms_rotate_gpu
    Tout=tf.int64)
  File "/home/dlmu/.virtualenvs/dl2cv/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 457, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/dlmu/.virtualenvs/dl2cv/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 253, in _internal_py_func
    token = _py_funcs.insert(func)
  File "/home/dlmu/.virtualenvs/dl2cv/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 141, in insert
    self._funcs[token] = func
  File "/usr/lib/python2.7/weakref.py", line 108, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/usr/lib/python2.7/weakref.py", line 278, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'builtin_function_or_method' object
Segmentation fault (core dumped)
看到你之前回答说要封装cython，能说的详细些吗？谢谢

**Comment by ryanjay0** [comment]
Can you please explain how to wrap this function and fix the error? How do you not get the error with this code?

**Comment by wizholy** [comment]
我也碰到这个问题了，能问下怎么处理吗
