### ISSUE TITLE
bug in training my own data

### ISSUE THREAD

**Issue by haibucuo0** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#49]
Hi,
    Have you ever had this problem? How to solve it?Thanks.
2019-02-27 10:55:33.007891: W tensorflow/core/framework/op_kernel.cc:1158] Unknown: exceptions.KeyError: 2
2019-02-27 10:55:33.057396: W tensorflow/core/framework/op_kernel.cc:1158] Unknown: exceptions.KeyError: 2
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_15", _device="/job:localhost/replica:0/task:0/cpu:0"](Squeeze_1/_1363, postprocess_fastrcnn_r/Gather_4/_1365, postprocess_fastrcnn_r/Gather_6/_1367, postprocess_fastrcnn_r/Gather_5/_1369)]]
2019-02-27 10:55:33.057436: W tensorflow/core/framework/op_kernel.cc:1158] Unknown: exceptions.KeyError: 2
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_15", _device="/job:localhost/replica:0/task:0/cpu:0"](Squeeze_1/_1363, postprocess_fastrcnn_r/Gather_4/_1365, postprocess_fastrcnn_r/Gather_6/_1367, postprocess_fastrcnn_r/Gather_5/_1369)]]
2019-02-27 10:55:33.057453: W tensorflow/core/framework/op_kernel.cc:1158] Unknown: exceptions.KeyError: 2
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_15", _device="/job:localhost/replica:0/task:0/cpu:0"](Squeeze_1/_1363, postprocess_fastrcnn_r/Gather_4/_1365, postprocess_fastrcnn_r/Gather_6/_1367, postprocess_fastrcnn_r/Gather_5/_1369)]]
2019-02-27 10:55:33.635849: W tensorflow/core/framework/op_kernel.cc:1158] Unknown: exceptions.KeyError: 2
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_15", _device="/job:localhost/replica:0/task:0/cpu:0"](Squeeze_1/_1363, postprocess_fastrcnn_r/Gather_4/_1365, postprocess_fastrcnn_r/Gather_6/_1367, postprocess_fastrcnn_r/Gather_5/_1369)]]
2019-02-27 10:55:33.644552: W tensorflow/core/kernels/queue_base.cc:294] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-02-27 10:55:33.644611: W tensorflow/core/kernels/queue_base.cc:294] _0_get_batch/input_producer: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/ubuntu/R2CNN_Faster-RCNN_Tensorflow/tools/train.py", line 213, in <module>
    train()
  File "/home/ubuntu/R2CNN_Faster-RCNN_Tensorflow/tools/train.py", line 193, in train
    _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: exceptions.KeyError: 2
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_15", _device="/job:localhost/replica:0/task:0/cpu:0"](Squeeze_1/_1363, postprocess_fastrcnn_r/Gather_4/_1365, postprocess_fastrcnn_r/Gather_6/_1367, postprocess_fastrcnn_r/Gather_5/_1369)]]

Caused by op u'PyFunc_1', defined at:
  File "/home/ubuntu/R2CNN_Faster-RCNN_Tensorflow/tools/train.py", line 213, in <module>
    train()
  File "/home/ubuntu/R2CNN_Faster-RCNN_Tensorflow/tools/train.py", line 74, in train
    scores=final_scores_r)
  File "/home/ubuntu/R2CNN_Faster-RCNN_Tensorflow/libs/box_utils/show_box_in_tensor.py", line 238, in draw_boxes_with_categories_and_scores_rotate
    Tout=[tf.uint8])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 198, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 38, in _py_func
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

UnknownError (see above for traceback): exceptions.KeyError: 2
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_15", _device="/job:localhost/replica:0/task:0/cpu:0"](Squeeze_1/_1363, postprocess_fastrcnn_r/Gather_4/_1365, postprocess_fastrcnn_r/Gather_6/_1367, postprocess_fastrcnn_r/Gather_5/_1369)]]

Process finished with exit code 1

**Comment by haibucuo0** [comment]
Is the reason for the error in the “class_num ” settings
