### ISSUE TITLE
faster_rcnn.build_whole_detection_network的参数不对

### ISSUE THREAD

**Issue by Learningchen** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#61]
Traceback (most recent call last):                                                                         │····················
  File "multi_gpu_train.py", line 227, in <module>                                                         │····················
    train()                                                                                                │····················
  File "multi_gpu_train.py", line 143, in train                                                            │····················
    fastrcnn_loc_loss, fastrcnn_cls_loss, fastrcnn_total_loss = tower_loss(scope)                          │····················
  File "multi_gpu_train.py", line 48, in tower_loss                                                        │····················
    gtboxes_batch=gtboxes_and_label)                                                                       │····················
TypeError: build_whole_detection_network() got an unexpected keyword argument 'gtboxes_batch'              │····················
(py2.7_tf_1.3) chenyao@ubuntu:/data4/chenyao/RRPN_Faster-RCNN_Tensorflow/tools$ ls

**Comment by zdgithub** [comment]
我想用多gpu训练运行时也遇到了这个问题

**Comment by yangxue0827** [comment]
这个repo多gpu我没有改，需要参考fpn的修改一下就行  @Learningchen @zdgithub
