### ISSUE TITLE
when i run: python camera_demo.py --gpu='0'

### ISSUE THREAD

**Issue by ZhangHe95** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#64]
Traceback (most recent call last):
  File "camera_demo.py", line 16, in <module>
    from libs.networks import build_whole_network
  File "../libs/networks/build_whole_network.py", line 19, in <module>
    from libs.detection_oprations.anchor_target_layer_without_boxweight import anchor_target_layer
  File "../libs/detection_oprations/anchor_target_layer_without_boxweight.py", line 15, in <module>
    from libs.box_utils.cython_utils.cython_bbox import bbox_overlaps
ImportError: dynamic module does not define module export function (PyInit_cython_bbox)

**Comment by yangxue0827** [comment]
you need to compile the module. @ZhangHe95
