### ISSUE TITLE
TypeError: cannot create weak reference to 'builtin_function_or_method' object

### ISSUE THREAD

**Issue by liugaolian** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#81]
My environment ：  tensorflow1.13.2/python2.7

**Comment by liugaolian** [comment]
When I execute ：python camera_demo.py --gpu='0'
The following error occurred，can you help me？
Traceback (most recent call last):
  File "camera_demo.py", line 138, in <module>
    inference(det_net, cap)
  File "camera_demo.py", line 48, in inference
    gtboxes_r_batch=None)
  File "../libs/networks/build_whole_network.py", line 538, in build_whole_detection_network
    img_shape=img_shape)
  File "../libs/networks/build_whole_network.py", line 154, in postprocess_fastrcnn_r
    use_gpu=cfgs.ROTATE_NMS_USE_GPU)
  File "../libs/box_utils/nms_rotate.py", line 31, in nms_rotate
    device_id=gpu_id)
  File "../libs/box_utils/nms_rotate.py", line 101, in nms_rotate_gpu
    Tout=tf.int64)
  File "/root/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 468, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/root/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 254, in _internal_py_func
    token = _py_funcs.insert(func)
  File "/root/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 142, in insert
    self._funcs[token] = func
  File "/root/anaconda3/envs/py2/lib/python2.7/weakref.py", line 108, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/root/anaconda3/envs/py2/lib/python2.7/weakref.py", line 278, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'builtin_function_or_method' object

**Comment by liuyong81** [comment]
I have the same problem which has not been resolved.  
TypeError: cannot create weak reference to 'builtin_function_or_method' object

**Comment by liugaolian** [comment]
> I have the same problem which has not been resolved.
> TypeError: cannot create weak reference to 'builtin_function_or_method' object

hello，you must install tensorflow1.2 ！
I do that，it's work！！！
