### ISSUE TITLE
NameError: name 'NAME_LABEL_MAP' is not defined

### ISSUE THREAD

**Issue by kokozeng** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#99]
when i use convert_data_to_tfrecord.py
the traceback was:
```
Traceback (most recent call last):
  File "convert_data_to_tfrecord.py", line 10, in <module>
    from libs.label_name_dict.label_dict import *
  File "../../libs/label_name_dict/label_dict.py", line 79, in <module>
    LABEl_NAME_MAP = get_label_name_map()
  File "../../libs/label_name_dict/label_dict.py", line 75, in get_label_name_map
    for name, label in NAME_LABEL_MAP.items():
NameError: name 'NAME_LABEL_MAP' is not defined
```

i don't know how to fix it.
i add one dataset in label.dict.py.

**Comment by vasanththangavel** [comment]
@kokozeng In label_dict.py File make this change
elif cfgs.DATASET_NAME == 'CUSTOM':
    NAME_LABEL_MAP = {
        'back_ground': 0,
        'Custom': 1
    }
